name: Latest blog post

on:
  schedule: 
    - cron: '0 17 * * *' 
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in latest posts from Unicast
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          commit_message: "Workflow updated readme with the latest blog post data"
          feed_list: "https://diegosrp.github.io/feed.xml"
          max_post_count: 5
